name: Build Pipeline

on:
  workflow_dispatch:
    inputs:
      linux_arch:
        description: 'Linux x64'
        required: true
        default: 'linux-x64'
      windows_arch:
        description: 'Windows x64'
        required: true
        default: 'win-x64'
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make Build Script Executable
        run: chmod +x Scripts/build.sh

      - name: Build for Linux
        run: ./Scripts/build.sh ${{ github.event.inputs.linux_arch }}

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: ./Artifacts/**

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make Build Script Executable (WSL)
        run: wsl chmod +x Scripts/build.sh

      - name: Build for Windows (WSL)
        run: wsl ./Scripts/build.sh ${{ github.event.inputs.windows_arch }}

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: ./Artifacts/**