name: Build Pipeline

on:
  workflow_dispatch:
    inputs:
      linux_arch:
        description: 'Linux x64'
        required: true
        default: 'linux-x64'
      windows_arch:
        description: 'Windows x64'
        required: true
        default: 'win-x64'
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      LINUX_ARCH: 
        ${{ github.event.inputs.linux_arch || 'linux-x64' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make Build Script Executable
        run: chmod +x Scripts/build.sh

      - name: Build for Linux
        run: cd Scripts && ./build.sh ${{ env.LINUX_ARCH }}

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: Artifacts/**

  build-windows:
    runs-on: windows-latest
    env:
      WINDOWS_ARCH:
        ${{ github.event.inputs.windows_arch || 'win-x64' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make Build Script Executable (WSL)		#BUG Fails for some reason
        run: wsl chmod +x Scripts/build.sh

      - name: Build for Windows (WSL)
        run: wsl cd Scripts && ./build.sh ${{ env.WINDOWS_ARCH }}

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: Artifacts/**